language: java
jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6
  - oraclejdk8
install: /bin/true
sudo: false
script:
  - echo "MAVEN_OPTS='-Xmx768m -XX:MaxPermSize=512m'" > ~/.mavenrc
  - mvn install -pl \!aws-java-sdk-osgi

